[general]
import = [ "~/.config/alacritty/nord.toml" ]

[window]
dimensions      = { columns = 90, lines = 40 }
dynamic_padding = true
option_as_alt   = "OnlyLeft"
padding         = { x = 12, y = 12 }

[font]
bold        = { family = "Pragmata", style = "Bold" }
bold_italic = { family = "Pragmata", style = "Bold Italic" }
italic      = { family = "Pragmata", style = "Italic" }
normal      = { family = "Pragmata", style = "Regular" }
offset      = { x = -1, y = -1 }
size        = 15
