import = [ "~/.config/alacritty/wildcharm_light.toml" ]

[window]
dimensions = { columns = 80, lines = 25 }
padding = { x = 12, y = 12 }
dynamic_padding = true
option_as_alt = "OnlyLeft"

[font]
normal = { family = "Pragmata", style = "Regular" }
bold = { family = "Pragmata", style = "Bold" }
italic = { family = "Pragmata", style = "Italic" }
bold_italic = { family = "Pragmata", style = "Bold Italic" }
size = 14.5
offset = { x = 0, y = 1 }
