import = [ "~/.config/alacritty/papercolor_dark.toml" ]

[window]
dimensions = { columns = 100, lines = 50 }
padding = { x = 12, y = 12 }
dynamic_padding = true
option_as_alt = "OnlyLeft"

[font]
normal = { family = "Pragmata", style = "Regular" }
bold = { family = "Pragmata", style = "Bold" }
italic = { family = "Pragmata", style = "Italic" }
bold_italic = { family = "Pragmata", style = "Regular Italic" }
size = 14
