import = [ "~/.config/alacritty/wildcharm_light.toml" ]

[window]
dimensions = { columns = 100, lines = 40 }
padding = { x = 10, y = 10 }
dynamic_padding = true
option_as_alt = "OnlyLeft"

[font]
normal = { family = "Pragmata", style = "Regular" }
bold = { family = "Pragmata", style = "Bold" }
italic = { family = "Pragmata", style = "Italic" }
bold_italic = { family = "Pragmata", style = "Bold Italic" }
size = 14.5
