# Designed to match the vim theme wildcharm dark. 

# Default colors
[colors.primary]
background = '#000000'
foreground = '#dadada'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#ff5f87'
green   = '#00d75f'
yellow  = '#ffaf00'
blue    = '#00afff'
magenta = '#ff00af'
cyan    = '#00d7d7'
white   = '#ffffff'

# Bright colors
[colors.bright]
black   = '#111111'
red     = '#d7005f'
green   = '#00d75f'
yellow  = '#ffaf00'
blue    = '#0087d7'
magenta = '#ff87ff'
cyan    = '#00afaf'
white   = '#eeeeee'
