# Designed to match the vim theme wildcharm light. 

# Default colors
[colors.primary]
background = '#d7d7d7'
foreground = '#000000'

# Normal colors
[colors.normal]
black   = '#ffffff'
red     = '#af0000'
green   = '#008700'
yellow  = '#af5f00'
blue    = '#005faf'
magenta = '#ff00af'
cyan    = '#008787'
white   = '#000000'

# Bright colors
[colors.bright]
black   = '#eeeeee'
red     = '#d70000'
green   = '#008700'
yellow  = '#d78700'
blue    = '#005faf'
magenta = '#af00af'
cyan    = '#0087d7'
white   = '#111111'
