theme = "base16_transparent"

[editor]
cursorline = true
true-color = true
rulers = [80, 100]
color-modes = true
popup-border = "all"
mouse = true
line-number = "relative"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "diagnostics"]
center = ["read-only-indicator", "file-name", "file-modification-indicator"]
right = ["selections", "register", "position"]
