theme = "tokyonight"

[editor]
scrolloff = 9
mouse = false
line-number = "relative"
rulers = [80, 100, 120]
bufferline = "multiple"
color-modes = true
popup-border = "all"

[editor.statusline]
left = ["mode", "spinner", "workspace-diagnostics"]
center = ["file-name", "file-modification-indicator"]
right = ["register", "selections", "position-percentage"]
mode.normal = "N"
mode.insert = "I"
mode.select = "S"

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "┆"
