[[language]]
name = "swift"
indent = { tab-width = 2, unit = "\t" }

[[language]]
name = "go"
indent = { tab-width = 2, unit = "\t" }

[[language]]
name = "rust"
indent = { tab-width = 2, unit = "\t" }
